name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: t1.4
      id: t1-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.4
        setup-command: ''
        command: grep -q -i -E 'docker.*run' answers/1.4 && grep -q -i -E '\-p=?\s?[[:digit:]]+:[[:digit:]]+'
          answers/1.4
        timeout: 10
        max-score: 10
    - name: t1.5
      id: t1-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.5
        setup-command: ''
        command: grep -q -i -E 'docker.*run' answers/1.5 && grep -q -i -E '\-p=?\s?[[:digit:]]+:[[:digit:]]+'
          answers/1.5 && grep -q -i -E '\-e=?\s?environment=?\s?[[:alnum:]]+' answers/1.5
        timeout: 10
        max-score: 10
    - name: t1.6
      id: t1-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.6
        setup-command: ''
        command: grep -q -i -E 'docker.*push.*[[:alnum:]]+/[[:alnum:]]+:[[:alnum:]]+'
          answers/1.6
        timeout: 10
        max-score: 10
    - name: t1.7
      id: t1-7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.7
        setup-command: ''
        command: grep -q -i -E 'docker.*rmi.*[[:alnum:]]+' answers/1.7
        timeout: 10
        max-score: 10
    - name: t1.8
      id: t1-8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.8
        setup-command: ''
        command: grep -q -i -E 'docker.*run' answers/1.8 && grep -q -i -E '\-d' answers/1.8
        timeout: 10
        max-score: 10
    - name: t1.9.1
      id: t1-9-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.9.1
        setup-command: ''
        command: grep -q -i -E 'docker.*ps' answers/1.9.1
        timeout: 10
        max-score: 10
    - name: t1.9.2
      id: t1-9-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.9.2
        setup-command: ''
        command: grep -q -i -E 'docker.*run' answers/1.9.2 && grep -q -i -E '\-\-name=?\s?.*'
          answers/1.9.2
        timeout: 10
        max-score: 10
    - name: t1.10
      id: t1-10
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.10
        setup-command: ''
        command: 'grep -q -i -E ''docker.*exec'' answers/1.10 && grep -q -i -E ''\-i?t?.*''
          answers/1.10 '
        timeout: 10
        max-score: 10
    - name: t1.12
      id: t1-12
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.12
        setup-command: ''
        command: grep -q -i -E 'docker.*run' answers/1.12 && grep -q -i -E '\-e=?\s?ws_back_url=?\s?[[:alnum:]]'
          answers/1.12
        timeout: 10
        max-score: 10
    - name: t1.14
      id: t1-14
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.14
        setup-command: ''
        command: grep -q -i -E 'docker.*stop' answers/1.14
        timeout: 10
        max-score: 10
    - name: t2.1
      id: t2-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t2.1
        setup-command: ''
        command: grep -q -i -E 'docker-compose.*up' answers/2.1
        timeout: 10
        max-score: 10
    - name: t2.6.1
      id: t2-6-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t2.6.1
        setup-command: ''
        command: grep -q -i -E 'docker-compose.*up.*\-d' answers/2.6.1
        timeout: 10
        max-score: 10
    - name: t2.6.2
      id: t2-6-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t2.6.2
        setup-command: ''
        command: grep -q -i -E 'docker-compose.*logs' answers/2.6.2
        timeout: 10
        max-score: 10
    - name: t2.8
      id: t2-8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t2.8
        setup-command: ''
        command: grep -q -i -E 'docker-compose.*scale' answers/2.8
        timeout: 10
        max-score: 10
    - name: t1.3
      id: t1-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: t1.3
        setup-command: ''
        command: grep -q -E 'docker.*run' answers/1.3
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T1-4_RESULTS: "${{steps.t1-4.outputs.result}}"
        T1-5_RESULTS: "${{steps.t1-5.outputs.result}}"
        T1-6_RESULTS: "${{steps.t1-6.outputs.result}}"
        T1-7_RESULTS: "${{steps.t1-7.outputs.result}}"
        T1-8_RESULTS: "${{steps.t1-8.outputs.result}}"
        T1-9-1_RESULTS: "${{steps.t1-9-1.outputs.result}}"
        T1-9-2_RESULTS: "${{steps.t1-9-2.outputs.result}}"
        T1-10_RESULTS: "${{steps.t1-10.outputs.result}}"
        T1-12_RESULTS: "${{steps.t1-12.outputs.result}}"
        T1-14_RESULTS: "${{steps.t1-14.outputs.result}}"
        T2-1_RESULTS: "${{steps.t2-1.outputs.result}}"
        T2-6-1_RESULTS: "${{steps.t2-6-1.outputs.result}}"
        T2-6-2_RESULTS: "${{steps.t2-6-2.outputs.result}}"
        T2-8_RESULTS: "${{steps.t2-8.outputs.result}}"
        T1-3_RESULTS: "${{steps.t1-3.outputs.result}}"
      with:
        runners: t1-4,t1-5,t1-6,t1-7,t1-8,t1-9-1,t1-9-2,t1-10,t1-12,t1-14,t2-1,t2-6-1,t2-6-2,t2-8,t1-3
